Repository kmesh-net/orion, pull requests merged in 2025-09, with the labels that each got.

#73 Replace LruMap with TimedLruCache in OriginalDstCluster
  Cargo.lock
  orion-lib/Cargo.toml
  orion-lib/src/clusters/cluster.rs
  orion-lib/src/clusters/cluster/dynamic.rs
  orion-lib/src/clusters/cluster/original_dst.rs
  orion-lib/src/clusters/cluster/static.rs
Labels: lgtm, size/XL, approved

#90 Add event handler for metrics in HTTP client builder (regression fixed).
  orion-lib/src/transport/http_channel.rs
Labels: lgtm, size/S, approved

#89 Make CachedRoute hold references instead of owned values
  orion-lib/src/listeners/http_connection_manager.rs
Labels: lgtm, size/S, approved

#97 Add CI job to check copyright headers in Rust source files
  .github/workflows/ci.yml
Labels: lgtm, size/S, approved

#94 Implement AutoHostRewrite functionality in request handling
  orion-configuration/src/config/network_filters/http_connection_manager/route.rs
  orion-lib/src/listeners/http_connection_manager/route.rs
Labels: lgtm, size/L, approved

#109 Add policy IDs to RBAC internal structures.
  orion-configuration/src/config/network_filters/http_connection_manager/http_filters/http_rbac.rs
  orion-configuration/src/config/network_filters/network_rbac.rs
  orion-error/src/lib.rs
  orion-lib/src/event_error.rs
  orion-lib/src/listeners/filterchain.rs
  orion-lib/src/listeners/http_connection_manager.rs
Labels: lgtm, size/L, approved

#87 feat: add internal listener and upstream transport support
  Cargo.lock
  examples/internal-listener-demo/README.md
  examples/internal-listener-demo/internal_client.rs
  examples/internal-listener-demo/orion-config.yaml
  examples/internal-listener-demo/test_internal_config.sh
  orion-configuration/src/config/bootstrap.rs
  orion-configuration/src/config/cluster.rs
  orion-configuration/src/config/core.rs
  orion-configuration/src/config/listener.rs
  orion-configuration/src/config/network_filters/http_connection_manager.rs
  orion-configuration/tests/test_internal_listener.rs
  orion-data-plane-api/src/bootstrap_loader/bootstrap.rs
  orion-data-plane-api/src/decode.rs
  orion-data-plane-api/src/xds/client.rs
  orion-data-plane-api/src/xds/model.rs
  orion-format/src/bin/format-test.rs
  orion-format/src/grammar.rs
  orion-format/src/lib.rs
  orion-lib/src/clusters/balancers/default_balancer.rs
  orion-lib/src/clusters/cluster/dynamic.rs
  orion-lib/src/clusters/cluster/original_dst.rs
  orion-lib/src/clusters/load_assignment.rs
  orion-lib/src/listeners/filterchain.rs
  orion-lib/src/listeners/http_connection_manager.rs
  orion-lib/src/listeners/listener.rs
  orion-lib/src/listeners/listeners_manager.rs
  orion-proxy/conf/envoy-bootstrap-tlv-demo.yaml
  orion-proxy/conf/internal-listener-demo.yaml
  orion-proxy/conf/orion-runtime-tlv-demo.yaml
  orion-proxy/src/admin/config_dump.rs
  orion-tracing/src/lib.rs
Labels: size/XXL, approved
